### ISSUE TITLE
Increase the limit of notifications

### ISSUE THREAD

**Issue by mansona** [gitify-app/gitify#356]
Hi folks 👋 

First of all I would like to say thanks for an awesome application 🎉 It's really great and it is wonderful that it is available for free 😍 

I'm wondering if there is a way to expand the limit of 50 notifications? If someone could outline how this might be done I am happy to contribute the work if I am pointed in the right direction 👍

**Comment by jgsqware** [comment]
Hey thank for the app too, and would love to see this too

**Comment by manosim** [comment]
Thank you for your kind words - I'm glad that developers find it useful! It's been a really long time since I wrote this so I'm not 100% sure but I think the limit of 50 notifications is coming from the GitHub API.

Currently, I'm holding off from making more changes to the way we are fetching the notifications for now as I'm hoping that the GraphQL api will support notifications at some point(hopefully soon) and Gitify will definitely switch to that when it's ready.

**Comment by setchy** [comment]
This feature will be made easier once https://github.com/gitify-app/gitify/issues/823 is complete
