### ISSUE TITLE
[Feature Request] GitHub Actions Output

### ISSUE THREAD

**Issue by karimsa** [gitify-app/gitify#425]
Hi, there! Gitify seems cool, but it would be nice to be able to see GitHub actions outputs/runs for my repos in the menu bar as well. Right now, I use [hukum](https://github.com/abskmj/hukum) to do this. But it would be nice to have this in the menu bar instead of a CLI.

**Comment by ospfranco** [comment]
[Try my app](https://cidemon.com)

**Comment by aehlke** [comment]
@ospfranco please remove color from the menu bar icon

**Comment by setchy** [comment]
Thanks for raising this @karimsa.  

Unfortunately, due to the current [limitations of the GitHub Public APIs](https://github.com/gitify-app/gitify/issues/890), it's not feasible for us to find a workflow run based on the notification alone.  

As these limitations are relaxed, we'll be sure to include the new features into Gitify.  For now, I'm going to close as not planned

**Comment by ospfranco** [comment]
I think you are mistaken @setchy. I built a Menu Bar app that could get access to CI steps some years ago.

https://github.com/ospfranco/cidemon

![CleanShot 2024-04-03 at 07 56 26@2x](https://github.com/gitify-app/gitify/assets/1634213/0ab93873-c76a-4595-9146-d7a995641693)
