### ISSUE TITLE
Make the popup window resizeable

### ISSUE THREAD

**Issue by a2sheppy** [gitify-app/gitify#434]
Is there a reason the window isn't resizable? It would be nice if (a) it were resizable, and (b) the size were remembered across uses of the app, including across relaunches.

**Comment by setchy** [comment]
> @setchy Any chance you can also reopen this one? Gitify is great but not really practical to use for me because of this particular size limit. (zooming out does not help as it would make the text too small).

Do you have a suggestion on how you'd like to see this supported? Is this something you'd be willing to implement if agreeable by the maintainers?

**Comment by bmulholland** [comment]
@ssbarnea I want to back @setchy up here, and go one step further. Your comment at https://github.com/gitify-app/gitify/issues/1312#issuecomment-2733087493 isn't respectful to the work we do, for free, and so actually we're _less_ likely to reopen this at your request. Honestly I'd hesitate to even review a PR you'd submit, because we'd then have to maintain it afterward -- something you haven't demonstrated appreciation for.
