### ISSUE TITLE
[Bug] Error: gitify Depends on libappindicator3-1 but it is not installable on Debian Bullseye

### ISSUE THREAD

**Issue by brianrobt** [gitify-app/gitify#505]
I'm using the Debian testing branch and trying to install the
latest .deb package with "dpkg -i -a gitify_4.2.1_amd64.deb" or with
"sudo apt install gitify_4.2.1_amd64.deb", I get the same error message
that a dependency cannot be found ("libappindicator3-1").  When running
"apt-cache search libappindicator", I can see that the available package
is "libappindicator3-0.1-cil".

```sh
$ apt-cache search libappindicator
libappindicator3-0.1-cil - CLI binding for libayatana-appindicator3 using GObject introspection
libappindicator3-0.1-cil-dev - CLI binding for libayatana-appindicator3 using GObject introspection
haskell-status-notifier-item-utils - StatusNotifierItem/libappindicator dbus implementation
libghc-status-notifier-item-dev - StatusNotifierItem/libappindicator dbus implementation
libghc-status-notifier-item-doc - StatusNotifierItem/libappindicator dbus implementation; documentation
libghc-status-notifier-item-prof - StatusNotifierItem/libappindicator dbus implementation; profiling libraries
```

It looks like the issue is because `libappindicator3-1` hasn't been
promoted from sid to testing yet.

- libappindicator in sid: https://packages.debian.org/search?suite=sid&arch=any&searchon=names&keywords=libappindicator
- libappindicator in testing: https://packages.debian.org/search?suite=bullseye&arch=any&searchon=names&keywords=libappindicator

**Comment by thompsonbrian** [comment]
After some further digging, I found out that libappindicator has been deprecated in Debian as of the Bullseye release (11.0).  It is being replaced by libayatana-appindicator: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

Currently the `.deb` file is being packaged with the default dependencies: `["gconf2", "gconf-service", "libnotify4", "libappindicator1", "libxtst6", "libnss3"]`

`libappindicator1` should be replaced with `libayatana-appindicator1`, which can be set in the `package.json`.  I don't think this would break the existing Ubuntu 18.04 target since  `libayatana-appindicator1` is available, but I haven't tested that: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libayatana-appindicator1&searchon=names

**Comment by brianrobt** [comment]
This issue has been fixed.  Closing it out.
