### ISSUE TITLE
Links to discussions don't work

### ISSUE THREAD

**Issue by martinjagodic** [gitify-app/gitify#521]
I get notifications for issues, pull requests, and discussions in Gitify, but only issues and PRs are clickable. To see the discussion I have to open each repo individually and navigate there, so a clickable discussion notification would do wonders.

**Comment by codebytere** [comment]
@martinjagodic the issue lies unfortunately with GitHub - the Notifications API is somewhat......lacking in many areas. The payload for a call to [fetch notifications for an authed user](https://docs.github.com/en/rest/reference/activity#list-notifications-for-the-authenticated-user) has a subject property:

```
   "subject": {
      "title": "Greetings",
      "url": "https://api.github.com/repos/octokit/octokit.rb/issues/123",
      "latest_comment_url": "https://api.github.com/repos/octokit/octokit.rb/issues/comments/123",
      "type": "Issue"
    },
```

and for Discussions, `subject.url` is always `null` because it seems that the backend is not filling it properly for newer notification types like Discussions. There's https://github.com/manosim/gitify/pull/487 up to try to triage this but it'll only really be fixed once the GitHub API team figures it out.

**Comment by bmulholland** [comment]
Is there anywhere to +1 the issue with Github?

**Comment by jamesdh** [comment]
@bmulholland easiest thing is to probably go to https://support.github.com and open a new issue there. I've had pretty good success with getting the attention of their engineers through that channel. Unfortunately I don't believe they offer any way to make your support ticket public (for upvotes).

**Comment by bmulholland** [comment]
I finally got bothered enough to look to file a ticket with Github, and I got routed to their Discussions where they gather feedback. https://github.com/github/feedback/discussions/categories/discussions-feedback?discussions_q=notifications+api+url+category%3A%22Discussions+Feedback%22

I've created a discussion item for this, please go +1 it: https://github.com/github/feedback/discussions/15252

**Comment by jamesdh** [comment]
You'll probably have the most luck going to https://support.github.com and filing a support ticket there. That should actually be received by an engineer. As opposed to their more public facing community platform which, from my experience, isn't monitored by their engineering team and instead has community moderators who do a terrible job of bubbling up issues appropriately. 

I've used their lesser known support system numerous times and have gotten responses directly from engineers at GitHub almost every time. I'd suggest

**Comment by jamesdh** [comment]
Just realized I left basically the same comment ~5 months ago  🤦🏻‍♂️

**Comment by bmulholland** [comment]
Though now at least there's _something_ to +1, even if it's not a support ticket and may not get seen by an engineer

**Comment by bmulholland** [comment]
Here's what I got back from Github support -- something doesn't line up, but I'm not knowledgeable enough to connect the dots. Obviously there is _some_ support for Discussions, since they show up in the notifications. Anyway, it's hard for me to move this forward without investing significantly more time.

> Discussions are not currently available via our REST API so there isn't anywhere for the url field to point to at the moment. I'm sorry not to have better news for you!
> 
> There is an open internal issue tracking this as a feature request and I have added your +1 to the list. At the point when discussions are available to REST API, you'd be able to make use of those notifications, but I don't have an ETA on when that will happen. I'd suggest keeping an eye on our [changelog](https://docs.github.com/en/graphql/overview/changelog) and [blog](https://github.blog/) where we make announcements on new features.

**Comment by bmulholland** [comment]
@Dentrax In the OSS world, pinging people is considered rude. There's no relationship here where anyone owes us anything.

**Comment by Dentrax** [comment]
Thanks for the warning, I'm already aware of that behavior.

> In the OSS world, pinging people is considered rude.

It's a subjective statement. "rude" is a way too strong word. Anyone can ping me anytime, anywhere; I don't mind, always ready to help. I would even drop a small thank for reminding. So, I don't see any "rude" behavior here.

Since more than 8 months passed and no update on this (+ no stale bot impl on this repo), people may have forgotten. Let's focus on the problem and alternative solutions, or kindly ignore the "ping".

**Comment by jamesdh** [comment]
The greater issue at hand currently is that this repo/project are effectively abandoned. I think going forward, the only way for issues like this one to be fixed is for someone to fork it and take matters into their own hands. For whatever reason, the creators/collaborators of this repo seem to have lost all interest in it and aren't willing to assign others to help out. 

More specific to this issue, there is a [fix](https://github.com/manosim/gitify/pull/538) (using the GraphQL API) and a [workaround](https://github.com/manosim/gitify/pull/487/files) (simply forwarding to the Repo's Discussions page) already PR'd, but again, without anyone willing to review/merge/release, they aren't much help currently.

**Comment by bmulholland** [comment]
See https://github.com/manosim/gitify/issues/545
