### ISSUE TITLE
Links to deploy actions do not work

### ISSUE THREAD

**Issue by ianaya89** [gitify-app/gitify#526]
We use GH actions with a deployment pipeline. I get the notification but clicking on it does not open the URL.
It's something quite new, so I guess it is not supported yet, but I think it would be a great addition.

Let me know if you need more info, happy to help

![140758396-9f68d017-8556-4cb4-9b44-1ab5d65c36a8](https://user-images.githubusercontent.com/3258966/140759236-54bc2910-4e56-4855-9100-8d0b8261c9cb.png)

PS: I love this tool, it saved me from GitHub fatigue ❤️

**Comment by codebytere** [comment]
@ianaya89 ooh, thanks! Sometimes GitHub does this - they add new types without documenting them. I'm not sure we can properly fix up the links, since GitHub doesn't fill in the Notification URLs for newer stuff in their REST API, but we can at least get a nice icon and fix up the type in there. I'll see what I can do!

**Comment by ianaya89** [comment]
Makes sense, that would a good solution. Thanks for your quick reply :)
